### ISSUE TITLE
How to use this library in the web front-end

### ISSUE THREAD

**Issue by sufuf3** [substack/deep-freeze#14]
Hi @substack   , 
I'm a member of [cdnjs](https://github.com/cdnjs/cdnjs), which is the FOSS web front-end resource CDN. 
I want to know how to use this library in the web front-end.
I tried and it seems that need to use in the web back-end.

If you have any suggestions, please let me know.
Thank you.

cdnjs/cdnjs#8231
cdnjs/cdnjs#10466

**Comment by rattrayalex** [comment]
It will need to be forked or wrapped to be used without browserify/webpack/similar. 

You can accomplish this in a fork by changing the first line to 

```js
window.deepFreeze = function deepFreeze (o) {
```
or, better yet, 
```js
function deepFreeze (o) {
```
and at the end of the file, 
```js
if (typeof module !== "undefined" && module.exports) {
  module.exports = deepFreeze;
}
if (typeof window !== "undefined") {
  window.deepFreeze = deepFreeze;
}
```

That may not be the best way – I haven't written such shims before and don't know of a best-practice – but it should work.

**Comment by sufuf3** [comment]
@rattrayalex thank you.
It seems that I should modify the `index.js` then it can use in web front-end.
But CDNJS is web front-end resource, so we don't modify the file.
Is there any way to include the library and use it in front-end?

**Comment by rattrayalex** [comment]
Hmm, maybe try asking a cdnjs maintainer how they've solved this in the past?

**Comment by sufuf3** [comment]
cdnjs host the web front-end library. 
I just want to know that how to include this library and use it in web front-end?
cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
We do nothing on this, unless the author wants to make it can be hosted on CDN, we don't host it in this case.

**Comment by sufuf3** [comment]
OK! Thanks.
