### ISSUE TITLE
Attributes remain frozen when making a copy of a deepFreeze Object 

### ISSUE THREAD

**Issue by jwlms** [substack/deep-freeze#18]
After invoking `deepFreeze()` on an Object and then making a copy of that with `Object.assign` or through the spread operator, the attributes of that cloned Object (but not the Object itself) remain frozen.

Steps to Reproduce:

```js
let obj = { confused: true, someMutableArray: [1, 2, 3] };

Object.isFrozen(obj)
// true

let frozenObj = deepFreeze(obj);

let unfreeze = Object.assign({}, frozenObj);

Object.isFrozen(unfreeze)
// false (expect false)

Object.isFrozen(unfreeze['confused'])
// true (expect false)

Object.isFrozen(unfreeze['someMutableArray'])
// true (expect false)
```

I know that strictly speaking your package is about deepFreezing (and not necessarily concerned with unfreezing), but this behavior doesn't seem right.

Thanks for taking a look!

**Comment by sohailashraf003** [comment]
As you know objects are reference based, when you copy objects with `Object.assign` or with the spread operator, I will give a shallow copy. So the nested objects will still refer to the old object which is frozen. 

You have to deep clone to to solve your issue.

**Comment by jwlms** [comment]
That makes sense. Thanks!
