### ISSUE TITLE
deep-freeze: How to change object in array

### ISSUE THREAD

**Issue by wizardnet972** [substack/deep-freeze#8]
I have an array, and I dont know how to change it's values after I freeze it..

```

var x = [{ id: 1, items: [[{ n: 52, select: false }, { n: 64, select: false }, { n: 93, select: false }], [{ n: 22, select: false }, { n: 64, select: false }, { n: 3, select: false }], [{ n: 12, select: false }, { n: 84, select: false }, { n: 3, select: false }]] }, { id: 2, items: [[{ n: 52, select: false }, { n: 4, select: false }, { n: 93, select: false }], [{ n: 52, select: false }, { n: 5, select: false }, { n: 3, select: false }], [{ n: 52, select: false }, { n: 64, select: false }, { n: 3, select: false }]] }]

import * as deepFreeze from 'deep-freeze';
var y = deepFreeze(x);
```

I want to change where n===52 to select=true anywhere in this array without create new array or change reference location.

and Without using immutable.js

I need some help with this please.

**Comment by aluanhaddad** [comment]
@wizardnet972 the point of this library is that once you _deepFreeze_ something, you cannot mutate it.
Will not be able to mutate it. You can use this capability to ensure invariants, write code that is easier to reason about, more maintainable, and more robust.
